### ISSUE TITLE
include a facet for archive in document-search

### ISSUE THREAD

**Issue by cfhaak** [Flugblatter/flugblaetter_static#15]

**Comment by cfhaak** [comment]
done; 

@claudiar16 to me it looks like there are some errors in the data. Eg. Wienbibliothek seems to have a lot of settlements:
Wienbibliothek im Rathaus
Wienbibliothek im Rathaus, Abtenzell in Schwaben
Wienbibliothek im Rathaus, Brünn
Wienbibliothek im Rathaus, Graz
Wienbibliothek im Rathaus, Karlsburg im Großfürstentum 

is that an error?

**Comment by claudiar16** [comment]
Lieber Fritz,
das ist sehr merkwürdig -
ich würd mir das gerne ansehen;
kann ich morgen kurz vorbeikommen?
Ich bin vormittags auf der Uni, aber ab 13 Uhr am Institut - melde mich dann!
Danke und liebe Grüße
Claudia
________________________________
Von: cfhaak ***@***.***>
Gesendet: Mittwoch, 19. Juni 2024 15:59:03
An: Flugblatter/flugblaetter_static
Cc: Resch, Claudia; Mention
Betreff: [EXT] Re: [Flugblatter/flugblaetter_static] include a facet for archive in document-search (Issue #15)

External Email: please use links and attachments from trusted sources only

done;

@claudiar16<https://github.com/claudiar16> to me it looks like there are some errors in the data. Eg. Wienbibliothek seems to have a lot of settlements:
Wienbibliothek im Rathaus
Wienbibliothek im Rathaus, Abtenzell in Schwaben
Wienbibliothek im Rathaus, Brünn
Wienbibliothek im Rathaus, Graz
Wienbibliothek im Rathaus, Karlsburg im Großfürstentum

is that an error?
