### ISSUE TITLE
Punkte nach Jahreszahlen

### ISSUE THREAD

**Issue by claudiar16** [Flugblatter/flugblaetter_static#30]
![image](https://github.com/Flugblatter/flugblaetter_static/assets/49231272/f391d59b-e3b7-4bce-a109-198124a144ad)
Lieber Fritz, 
bei den Kurzanzeigen wird die Jahreszahl des Druckdatum (nur) manchmal mit einem Punkt beendet. 
Könntest Du den entfernen?

**Comment by cfhaak** [comment]
[fixed it via data repo, using the when attrib …](https://github.com/Flugblatter/flugblaetter_data_export/commit/c79b7ecfdd9a01a0e0c87d08dc95b0a893b7fa58)
