### ISSUE TITLE
Verschiedene Versionen des selben Flugblatts

### ISSUE THREAD

**Issue by claudiar16** [Flugblatter/flugblaetter_static#31]
Ich bin jetzt nicht sicher ... 

aber wenn es 2 Versionen des selben Flugblatts gibt: 
sollten beide als alternative Repräsentationen eines Flugblatts behandelt und auch angezeigt werden können 
(mit ihrer jeweils eigenen Transkription)

(denn wenn wir diese 2 Versionen als unterschiedliche Dokumente behandeln würden, würden statistische Abfragen ja immer fehlerhaft sein - oder?)

**Comment by cfhaak** [comment]
- [ ] Beide Dokumente werden für die Textansicht als eigenständig behandelt und mitsamt ihrer Bilder dargestellt
- [ ] Textvarianzen werden reziprok dargestellt und referenziert
- [ ] die Dokumentenansicht/-suche behandelt die differierenden Fassungen als ein Dokumenten, dass verschiedene Versionen aufweist und verlinkt diese ausgehend von der identitätsstiftenden Ansetzung

**Comment by cfhaak** [comment]
Slicing the docs will be necessary, either:
1 xml -> 2 xml -> 2 html
or 
1xml -> 2 html
the latter seems less komplex and it keeps the data structure as is, i'll thus try that

**Comment by cfhaak** [comment]
Or just keep the wf as is and then change the html?

**Comment by cfhaak** [comment]
https://getbootstrap.com/docs/5.0/components/navs-tabs/
https://getbootstrap.com/docs/4.0/components/modal/

This could be used to display only one doc in primary view. Other witnesses variants could be displayed in a classical apparatus, linking the images of the current page. Metadata should be displayed with tabs, also containing the images as thumbnails linking to the full sized images, maybe rendered via modal …?
